name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version string for the deployment'
        required: true
        default: '0.1.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      project: ${{secrets.PROJECT_ID}}
    steps:
      - name: 'auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{secrets.ECHO_GCA}}
          project_id: ${{ env.project }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ env.project }}
  
      - name: Deploy to Cloud Run
        run: |
          echo "$ENV_FILE" >> ./.env
          gcloud run deploy echo-be \
            --image asia-south1-docker.pkg.dev/echo-rag/echo/echo_be:${{ github.event.inputs.version }} \
            --memory=512Mi \
            --cpu=1 \
            --region=asia-south1 \
            --min-instances=0 \
            --max-instances=1 \
            --allow-unauthenticated \
            --env-vars-file=.env \
            --add-volume name=creds,type=cloud-storage,bucket=echo_creds \
            --add-volume-mount=volume=creds,mount-path=/usr/app/creds
        env:
          ENV_FILE: ${{ secrets.APP_ENV }}
      
  post-deploy:
    environment:
      name: 'version-${{ github.event.inputs.version }}'
      url: 'https://github.com/EchoRag/echo_be/releases/tag/${{ github.event.inputs.version }}'
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
        run: |
          gh release edit "$tag" \
              --latest